"""Fetch ICLR 2026 candidate papers relevant to mechanistic interpretability,
sparse autoencoders, and representation learning from the OpenReview API.

Uses the /notes/search endpoint (the plain /notes listing is behind an
anti-bot challenge). Search results include `venueid`, which lets us derive
acceptance status. We over-fetch with a broad keyword set, dedupe by forum id,
then apply a precision filter + tier heuristic.

Output:
  Research_Intelligence/Conferences/ICLR/2026/_cache_candidates.json
  (candidate_papers.md is generated by build_candidates_md.py)
"""
from __future__ import annotations
import json, time, sys, urllib.parse, urllib.request, urllib.error, pathlib, collections

BASE = "https://api2.openreview.net/notes/search"
GROUP = "ICLR.cc/2026/Conference"
OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "Conferences" / "ICLR" / "2026"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Search terms sent to OpenReview (broad recall).
SEARCH_TERMS = [
    "mechanistic interpretability", "sparse autoencoder", "sparse coding",
    "dictionary learning", "monosemanticity", "superposition", "polysemantic",
    "feature geometry", "representation geometry", "concept discovery",
    "concept bottleneck", "feature disentanglement", "activation patching",
    "path patching", "circuit discovery", "attribution patching",
    "activation steering", "representation steering", "steering vector",
    "concept vector", "linear representation hypothesis", "probing classifier",
    "causal probing", "causal representation learning", "representation similarity",
    "representation alignment", "neural collapse", "model editing",
    "knowledge editing", "machine unlearning", "faithfulness explanation",
    "feature visualization", "neuron interpretation", "transformer circuits",
    "refusal direction", "jailbreak detection", "latent monitoring",
    "self-supervised representation", "contrastive learning representation",
    "disentangled representation", "interpretability benchmark",
    "automated interpretability", "cross-layer transcoder", "attention head interpretability",
    "safety interpretability", "representation robustness", "prototype learning",
]

# High-precision keyword buckets used for filtering + tiering.
TIER1_KW = [
    "sparse autoencoder", "sparse auto-encoder", " sae ", "saes ", "(sae", "sae)",
    "mechanistic interpret", "monosemantic", "polysemantic", "superposition",
    "dictionary learning", "activation patching", "path patching",
    "attribution patching", "circuit", "steering vector", "activation steering",
    "representation steering", "concept vector", "linear representation",
    "feature geometry", "concept bottleneck", "refusal", "transcoder",
    "logit lens", "feature disentangl", "neuron interpret", "interpretable feature",
    "model internals", "residual stream", "crosscoder", "feature absorption",
    "feature splitting", "automated interpretability",
]
TIER1_AREA = {"interpretability and explainable ai"}
TIER2_KW = [
    "representation learning", "self-supervised", "contrastive",
    "disentangle", "causal representation", "representation similarity",
    "representation alignment", "neural collapse", "probing", "concept discovery",
    "faithfulness", "unlearning", "knowledge editing", "model editing",
    "ood detection", "out-of-distribution", "representation robustness",
    "prototype", "explainab", "interpretab", "latent space", "concept-based",
]

RAW_CACHE = OUT_DIR / "_raw_notes.json"

def _get(url, tries=6):
    delay = 3.0
    for attempt in range(tries):
        req = urllib.request.Request(url, headers={
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (research-intelligence)",
        })
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            if e.code == 429:
                print(f"    429; backoff {delay:.0f}s (attempt {attempt+1})", file=sys.stderr)
                time.sleep(delay)
                delay = min(delay * 2, 60)
                continue
            raise
        except Exception as e:
            print(f"    net error: {e}; retry", file=sys.stderr)
            time.sleep(delay)
            delay = min(delay * 2, 60)
    return None

def fetch_term(term, cap=300, page=100):
    notes = {}
    offset = 0
    while offset < cap:
        params = urllib.parse.urlencode({
            "term": term, "group": GROUP, "source": "forum",
            "limit": page, "offset": offset,
        })
        data = _get(f"{BASE}?{params}")
        if data is None:
            print(f"  ! giving up term={term!r} offset={offset}", file=sys.stderr)
            break
        batch = data.get("notes", [])
        for n in batch:
            notes[n["forum"]] = n
        if len(batch) < page:
            break
        offset += page
        time.sleep(1.2)
    return notes

def status_of(venueid: str) -> str:
    tail = venueid.split("/")[-1]
    return {
        "Conference": "accepted",
        "Rejected_Submission": "rejected",
        "Withdrawn_Submission": "withdrawn",
        "Desk_Rejected_Submission": "desk_rejected",
    }.get(tail, tail)

def text_blob(n) -> str:
    c = n["content"]
    parts = [c.get("title", {}).get("value", "")]
    parts += c.get("keywords", {}).get("value", []) or []
    parts.append(c.get("TLDR", {}).get("value", "") or "")
    parts.append(c.get("primary_area", {}).get("value", "") or "")
    return " \n ".join(parts).lower()

def matched(kws, blob):
    return [k.strip() for k in kws if k in blob]

def tier_of(n):
    blob = text_blob(n)
    area = (n["content"].get("primary_area", {}).get("value", "") or "").lower()
    t1 = matched(TIER1_KW, blob)
    t2 = matched(TIER2_KW, blob)
    if t1 or area in TIER1_AREA:
        return "tier-1", t1 or ["primary_area:interpretability"]
    if t2:
        return "tier-2", t2
    return None, []

def main():
    all_notes = {}
    if RAW_CACHE.exists():
        all_notes = json.loads(RAW_CACHE.read_text(encoding="utf-8"))
        print(f"loaded {len(all_notes)} cached raw notes")
    for i, term in enumerate(SEARCH_TERMS, 1):
        print(f"[{i}/{len(SEARCH_TERMS)}] {term}")
        got = fetch_term(term)
        for fid, n in got.items():
            all_notes[fid] = n
        print(f"    running unique={len(all_notes)}")
        RAW_CACHE.write_text(json.dumps(all_notes, ensure_ascii=False), encoding="utf-8")
        time.sleep(1.0)

    records = []
    for fid, n in all_notes.items():
        c = n["content"]
        venueid = c.get("venueid", {}).get("value", "")
        tier, kws = tier_of(n)
        if tier is None:
            continue
        records.append({
            "forum": fid,
            "title": c.get("title", {}).get("value", ""),
            "authors": c.get("authors", {}).get("value", []),
            "status": status_of(venueid),
            "venue": c.get("venue", {}).get("value", ""),
            "venueid": venueid,
            "primary_area": c.get("primary_area", {}).get("value", ""),
            "keywords": c.get("keywords", {}).get("value", []),
            "tldr": c.get("TLDR", {}).get("value", ""),
            "abstract": c.get("abstract", {}).get("value", ""),
            "tier": tier,
            "matched": kws,
            "pdf": c.get("pdf", {}).get("value", ""),
            "url": f"https://openreview.net/forum?id={fid}",
            "number": n.get("number"),
        })

    records.sort(key=lambda r: (r["tier"], {"accepted":0,"rejected":1,"withdrawn":2,"desk_rejected":3}.get(r["status"],9)))
    out = OUT_DIR / "_cache_candidates.json"
    out.write_text(json.dumps(records, indent=2, ensure_ascii=False), encoding="utf-8")

    by_status = collections.Counter(r["status"] for r in records)
    by_tier = collections.Counter(r["tier"] for r in records)
    acc_tier = collections.Counter(r["tier"] for r in records if r["status"]=="accepted")
    print("\nSaved", len(records), "candidate records ->", out)
    print("by status:", dict(by_status))
    print("by tier:", dict(by_tier))
    print("accepted by tier:", dict(acc_tier))

if __name__ == "__main__":
    main()
